### ISSUE TITLE
`try_from` not imported when using `single_render_pass` / `ordered_passes_renderpass`

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1846]
Possible regression introduced in https://github.com/vulkano-rs/vulkano/pull/1828,

```rust
error[E0599]: no variant or associated item named `try_from` found for enum `SampleCount` in the current scope
   --> src\interface\render\pipeline.rs:243:5
    |
243 | /                 single_pass_renderpass!(
244 | |                     self.bst.device(),
245 | |                     attachments: {
246 | |                         color: {
...   |
262 | |                     }
263 | |                 )
    | |_________________^ variant or associated item not found in `SampleCount`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: this error originates in the macro `$crate::ordered_passes_renderpass` (in Nightly builds, run with -Z macro-backtrace for more info)
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use std::convert::TryFrom;
```

**Comment by Rua** [comment]
`TryFrom` was added to the Rust prelude in the 2021 edition, so in principle it should never need to be imported. What edition is your project using?

**Comment by AustinJ235** [comment]
2018 edition 😆
