### ISSUE TITLE
Compile failure on Manjaro Linux

### ISSUE THREAD

**Issue by ProtoByter** [vulkano-rs/vulkano#1464]
# Template
*   Version of vulkano: 0.19
*   OS: Manjaro Linux
*   GPU (the selected PhysicalDevice): NVIDIA Geforce GTX 1650 Super
*   GPU Driver: NVIDIA 460.27.04
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: Not relavent

# Issue

Whenever I try and use vulkano I just get these error from cargo:

```
   Compiling vulkano v0.19.0
error[E0609]: no field `shaderf3264` on type `PhysicalDeviceFeatures`
   --> /home/protobit/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.19.0/src/features.rs:459:28
    |
459 |     core { shader_f3264 => shaderf3264 },
    |                            ^^^^^^^^^^^ help: a field with a similar name exists: `shaderInt64`

error[E0308]: mismatched types
    --> /home/protobit/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.19.0/src/command_buffer/sys.rs:1455:38
     |
1455 |         vk.CmdSetBlendConstants(cmd, constants); // TODO: correct to pass array?
     |                                      ^^^^^^^^^
     |                                      |
     |                                      expected `&[f32; 4]`, found array `[f32; 4]`
     |                                      help: consider borrowing here: `&constants`

error: aborting due to 2 previous errors
```
I'm unsure if it something wrong with my setup but I followed the setup in the README so idk what's wrong

**Comment by caandewiel** [comment]
Hi, I encountered the same issue and solved it by upgrading the vulkan version to 0.20.0 and downgrading the Vulkan SDK from 1.2 to 1.1

**Comment by Eliah-Lakhin** [comment]
@ProtoByter, @caandewiel Probably related to `f3264` naming issue fixed in version `0.20.0`: https://github.com/vulkano-rs/vulkano/commit/620b829bdb782bc15db7daf1b8c537ebcd1311c5#diff-d2ec10f741a852314cc59ac3d609fdfdf58f63e57b20885b32c7e83579dc92e4R1172 So, probably you need just to upgrade to the latest Vulkano.

LMK if it works. I would also like to know if it works with SDK 1.2. We don't yet fully support version 1.2, but I suppose it shouldn't lead to failures like this at least.

**Comment by ProtoByter** [comment]
Just tested it, it does compile when I set the dependency of vulkano to:
`vulkano = {git = "https://github.com/vulkano-rs/vulkano.git"}`

**Comment by alvinhochun** [comment]
It seems that `vk-sys` 0.5.3 contains a breaking change by renaming `shaderf3264` to `shaderFloat64`. This breaks semver. I believe it should've been released as 0.6 instead. Should `vk-sys` 0.5.3 be yanked?

**Comment by Eliah-Lakhin** [comment]
@alvinhochun Good point. Then we will have to yank other subproject too :/ ok, I will work on it, sorry for the issue.
